myquote/config/routes.rb
Rails.application.routes.draw do
  resources :quote_categories
  resources :categories
  resources :authors
  resources :quotes
  resources :users
  #get 'about/index'
  #get 'home/index'

  # Defines the root path route ("/")
  # root "articles#index"
  root "home#index"
  get '/about', to: 'about#index'
  get '/admin', to: 'home#aindex'
  get '/userhome', to: 'home#uindex'
  get '/your-quotes', to: 'home#uquotes'
  get 'search', to: 'search#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

myquote/app/models/quote_category.rb
class QuoteCategory < ApplicationRecord
  belongs_to :quote
  belongs_to :category
  validates :category_id, presence: true #Quote must have a category
  validates_uniqueness_of :category_id, scope: :quote_id #A quote can't have the same category twice
end

myquote/app/controllers/quote_categories_controller.rb
class QuoteCategoriesController < ApplicationController
  before_action :set_quote_category, only: %i[ show edit update destroy ]

  # GET /quote_categories or /quote_categories.json
  def index
    @quote_categories = QuoteCategory.all
  end

  # GET /quote_categories/1 or /quote_categories/1.json
  def show
  end

  # GET /quote_categories/new
  def new
    @quote_category = QuoteCategory.new
  end

  # GET /quote_categories/1/edit
  def edit
  end

  # POST /quote_categories or /quote_categories.json
  def create
    @quote_category = QuoteCategory.new(quote_category_params)

    respond_to do |format|
      if @quote_category.save
        format.html { redirect_to quote_category_url(@quote_category), notice: "Quote category was successfully created." }
        format.json { render :show, status: :created, location: @quote_category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @quote_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quote_categories/1 or /quote_categories/1.json
  def update
    respond_to do |format|
      if @quote_category.update(quote_category_params)
        format.html { redirect_to quote_category_url(@quote_category), notice: "Quote category was successfully updated." }
        format.json { render :show, status: :ok, location: @quote_category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @quote_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quote_categories/1 or /quote_categories/1.json
  def destroy
    @quote_category.destroy

    respond_to do |format|
      format.html { redirect_to quote_categories_url, notice: "Quote category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote_category
      @quote_category = QuoteCategory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def quote_category_params
      params.require(:quote_category).permit(:quote_id, :category_id)
    end
end

myquote/app/helpers/quote_categories_helper.rb
module QuoteCategoriesHelper
end

myquote/app/views/quote_categories/_form.html.erb
<%= form_with(model: quote_category) do |form| %>
  <% if quote_category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(quote_category.errors.count, "error") %> prohibited this quote_category from being saved:</h2>

      <ul>
        <% quote_category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :quote_id, style: "display: block" %>
    <%= form.text_field :quote_id %>
  </div>

  <div>
    <%= form.label :category_id, style: "display: block" %>
    <%= form.text_field :category_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

myquote/app/views/quote_categories/_quote_category.html.erb
<div id="<%= dom_id quote_category %>">
  <p>
    <strong>Quote:</strong>
    <%= quote_category.quote_id %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= quote_category.category_id %>
  </p>

</div>

myquote/app/views/quote_categories/edit.html.erb
<h1>Editing quote category</h1>

<%= render "form", quote_category: @quote_category %>

<br>

<div>
  <%= link_to "Show this quote category", @quote_category %> |
  <%= link_to "Back to quote categories", quote_categories_path %>
</div>

myquote/app/views/quote_categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Quote categories</h1>

<div id="quote_categories">
  <% @quote_categories.each do |quote_category| %>
    <%= render quote_category %>
    <p>
      <%= link_to "Show this quote category", quote_category %>
    </p>
  <% end %>
</div>

<%= link_to "New quote category", new_quote_category_path %>

myquote/app/views/quote_categories/new.html.erb
<h1>New quote category</h1>

<%= render "form", quote_category: @quote_category %>

<br>

<div>
  <%= link_to "Back to quote categories", quote_categories_path %>
</div>

myquote/app/views/quote_categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @quote_category %>

<div>
  <%= link_to "Edit this quote category", edit_quote_category_path(@quote_category) %> |
  <%= link_to "Back to quote categories", quote_categories_path %>

  <%= button_to "Destroy this quote category", @quote_category, method: :delete %>
</div>