myquote/config/routes.rb
Rails.application.routes.draw do
  resources :quote_categories
  resources :categories
  resources :authors
  resources :quotes
  resources :users
  #get 'about/index'
  #get 'home/index'

  # Defines the root path route ("/")
  # root "articles#index"
  root "home#index"
  get '/about', to: 'about#index'
  get '/admin', to: 'home#aindex'
  get '/userhome', to: 'home#uindex'
  get '/your-quotes', to: 'home#uquotes'
  get 'search', to: 'search#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

myquote/app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :author
  belongs_to :user
  has_many :quote_categories, dependent: :destroy
  has_many :categories, through: :quote_categories
  accepts_nested_attributes_for :quote_categories, reject_if: :all_blank, allow_destroy: true #Handle nested attributes
  validates :text, presence: true #Text can't be blank
  validates :author_id, presence: true #Author can't be blank
  validates :quote_categories, presence: true #Quote Categories can't be blank
  validates :text, uniqueness: {scope: :author_id, message: 'Quote text has already exist'} #Quote text must be unique
end

myquote/app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: %i[ show edit update destroy ]
  before_action :require_login, except: [:index, :show]
  before_action :user_edit, only: %i[ edit update destroy] #Limits access when edit, update, and destroy

  # GET /quotes or /quotes.json
  def index
    @quotes = Quote.includes(:categories).order(created_at: :desc)
  end

  # GET /quotes/1 or /quotes/1.json
  def show
    @quote = Quote.find(params[:id])
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
    7.times {@quote.quote_categories.build}  # Give the form SEVEN quote category fields
  end

  # GET /quotes/1/edit
  def edit
    (7 - @quote.quote_categories.count).times {@quote.quote_categories.build}  # Give the form up to SEVEN quote category fields
  end

  # POST /quotes or /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to quote_url(@quote), notice: "Quote was successfully created." }
        format.json { render :show, status: :created, location: @quote }
      else
        7.times {@quote.quote_categories.build}
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1 or /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to quote_url(@quote), notice: "Quote was successfully updated." }
        format.json { render :show, status: :ok, location: @quote }
      else
        (7 - @quote.quote_categories.count).times {@quote.quote_categories.build}
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1 or /quotes/1.json
  def destroy
    @quote.destroy

    respond_to do |format|
      format.html { redirect_to quotes_url, notice: "Quote was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def quote_params
      params.require(:quote).permit(:text, :year_publication, :comment, :is_public, :author_id, :user_id,
      quote_categories_attributes: [:id, :quote_id, :category_id])
    end

    #Denies access other quotes which isn't created by user
    def user_edit
      if @quote.user_id != current_user.id
        flash[:error] = "You are not allowed to access this quote"
        redirect_to quote_url(@quote)
      end
    end
end

myquote/app/helpers/quotes_helper.rb
module QuotesHelper
end

myquote/app/views/quotes/_form.html.erb
<%= form_with(model: @quote, local: true) do |f| %>
  <!-- This will display errors related to both the Quote and its nested QuoteCategories -->
  <% if @quote.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% @quote.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <!-- Hidden field for user_id -->
  <%= f.hidden_field :user_id, value: current_user.id %>

  <!-- Form fields associated with the quotes table -->
  <!-- Quote Text -->
  <div class="form-group" style="padding-bottom: 10px;">
    <%= f.text_field :text, placeholder: 'Quote Text*', class: 'form-control' %>
  </div>

  <!-- Quote Year Published -->
  <div class="form-group" style="padding-bottom: 10px;">
    <%= f.text_field :year_publication, placeholder: 'Quote Year Published', class: 'form-control' %>
  </div>

  <!-- Quote Comment -->
  <div class="form-group" style="padding-bottom: 10px;">
    <%= f.text_area :comment, placeholder: 'Quote Comment', class: 'form-control' %>
  </div>

  <!-- Quote is_public -->
  <div class="form-check" style="padding-bottom: 10px;">
    <%= f.label :is_public do %>
    Public
    <%= f.check_box :is_public, class: "form-check-input" %>
    <% end %>
  </div>

  <!-- Quote Author -->
  <div id="author-container" class="form-group" style="padding-bottom: 10px;">
      <%= f.label :author_id, "Author*", class: "form-label" %>
      <!-- Generates a selection of Author's in the database -->
      <%= f.select :author_id, [['Select an author', '']] + Author.order(:fname).collect {|a| ["#{a.fname} #{a.lname}", a.id] }, {inlude_blank: "Select an author"}, class: "form-control", style: "width: 300px;" %>
      <!-- Button to generate a new author which redirects to create new author -->
      <%= link_to "Add New Author", new_author_path %>
  </div>

  <br/>
  <!-- Quote Category -->
  <div id="categories-container" >
    <% @quote.quote_categories.each do |quote_category| %>
      <%= f.fields_for :quote_categories, quote_category do |ri| %>
        <div class="category-field row mb-2">
          <div class="col-auto">
            <!-- Create the dropdown list for selecting a category -->
            <%= ri.label :category_id, "Category*", class: "form-label d-inline-block me-2" %>
            <%= ri.select :category_id, [['Select a category', '']] + Category.all.collect { |ctg| [ctg.category_name, ctg.id] }, { include_blank: true }, class: "form-control d-inline-block" %>
          </div>
          <div class="col-auto align-self-end">
            <!-- Creates links to delete the category row when clicked -->
            <%= link_to '[-] Remove this Category', '#', class:'remove-category', style: "color: red; text-decoration: none;" %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

  <!-- Submit form button -->
  <div class="mt-3">
    <% if @quote.new_record? %>
      <%= f.submit 'Create', class: 'btn btn-primary btn-lg' %>
    <% else %>
      <%= f.submit 'Update', class: 'btn btn-primary btn-lg' %>
    <% end %>
  </div>
<% end %>

<!-- Javascript code on the remove categoru function -->
<script>
//Waits for document to be fully loaded
document.addEventListener('DOMContentLoaded', function() {
  //Detect clicks on any "Remove this category" links clicked by the user
  document.addEventListener('click', function(e) {
    //If an object with style class remove-category is clicked
    if (e.target && e.target.classList.contains('remove-category')) {
      //Prevent the link from behaving as links normally do, and instead
      e.preventDefault();

      //Make sure if the remove action executes, it won't leave us with no category
      const categoryFields = document.querySelectorAll('.category-field');
      //If at least one category will still reamin, then delete the one with which the link is associated
      if (categoryFields.length > 1) {
        e.target.closest('.category-field').remove();
      }
    }
  });
});
</script>

myquote/app/views/quotes/_quote.html.erb
<!-- Quote Details -->

<div id="<%= dom_id quote %>">
  <!-- Quote Text -->
  <h2>
    "<%= quote.text %>"
  </h2>

  <!-- Quote Category and Year Published -->
  <p>
    <strong>Categories:</strong>
    <%= quote.categories.map(&:category_name).join(", ") %><br />
    <strong>Year published:</strong>
    <%= quote.year_publication %>
  </p>

  <!-- Quote Author Details -->
  <p>
    <strong>Quote Author:</strong><br />
    <% if quote.author.death_year? %>
      <span class="author-indent" style="margin-left: 20px;"><%= "#{quote.author.fname} #{quote.author.lname} (#{quote.author.birth_year}-#{quote.author.death_year}) "%></span>
    <% else %>
      <span class="author-indent" style="margin-left: 20px;"><%= "#{quote.author.fname} #{quote.author.lname} (#{quote.author.birth_year}-present) "%></span>
    <% end %>
    <br/>
    <span class="author-indent" style="margin-left: 20px;"><%= quote.author.biography %></span>
  </p>

  <!-- Quote user publisher and comment (if there is a comment) -->
  <p>
    <strong>Published by:</strong><br />
    <span class="author-indent" style="margin-left: 20px;"><%= quote.user.fname %></span><br />
    <% if quote.comment.present? %>
      <span class="author-indent" style="margin-left: 20px;"><%= "Comment: #{quote.comment}" %></span>
    <% end %>
  </p>
</div>

myquote/app/views/quotes/edit.html.erb
<h1>Edit Quote</h1>
<br />

<%= render "form", quote: @quote %>

<br>

<div>
  <!-- Creates a link to show the quote when pressed -->
  <%= link_to "Show this quote", @quote %> |
  <!-- Creates a link to go back to whatever it's previous path -->
  <%= link_to "Back", :back %>
</div>

myquote/app/views/quotes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Quotes</h1>

<!-- Displays each quote -->
<% @quotes.each do |quote| %>
  <div class="card bg-body-tertiary" style="margin-bottom:10px">
  <div class="card-body">
    <h4 class="card-title">"<%= quote.text %>"</h4>
    <p class="card-text"><%= "- #{quote.author.fname} #{quote.author.lname}" %><br />[<a href="/quotes/<%=quote.id %>">Show this quote</a>]</p>
  </div>
  </div>
<% end %>

myquote/app/views/quotes/new.html.erb
<h1>New quote</h1>

<%= render "form", quote: @quote %>

<br>

<div>
  <!-- Creates a link to current_users quote when pressed -->
  <%= link_to "Back to My Quote", your_quotes_path %> |
  <!-- Creates a link to create a new quote when pressed -->
  <%= link_to "Create New Quote", new_quote_path %>
</div>

myquote/app/views/quotes/show.html.erb
<!-- Quotes being shown -->

<p style="color: green"><%= notice %></p>
<p class="error" style="color:red;"><%= flash[:error] %></p>

<%= render @quote %>

<!-- If user is logged in and published this quote -->
<% if logged_in? && current_user == @quote.user %>
  <div>
    <!-- Create links to edit quote and access my quote's' -->
    <%= link_to "Edit this quote", edit_quote_path(@quote) %> |
    <%= link_to "My Quotes", your_quotes_path %>
    <br/><br/>
    <!-- Create link to destroy quote. Intentionally placed it to prevent user from accidentally clicking it -->
    <%= button_to "Destroy this quote", @quote, method: :delete %>
  </div>
<!-- Else -->
<% else %>
  <div>
    <!-- Creates links to edit quote but it wont work and back to home page link -->
    <%= link_to "Edit this quote", edit_quote_path(@quote) %> |
    <%= link_to "Back Home", root_path %>
  </div>
<% end %>